name: Publish Docker image

on:
  release:
    types: published
  workflow_dispatch:

# Defines two custom environment variables for the workflow.
env:
  DOCKER_HUB_REGISTRY: docker.io
  GITHUB_REGISTRY: ghcr.io
  DOCKERFILE_DIR: ./src
  DOCKER_IMAGE_NAME: videoschnitt.engine

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
            ${{ env.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Print labels and tags
        run: |
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          file: ${{ env.DOCKERFILE_DIR }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        id: docker_build

      - name: Generate artifact attestation for the Docker Hub image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.DOCKER_HUB_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          subject-digest: ${{ steps.docker_build.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for the GitHub Container Registry image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.GITHUB_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          subject-digest: ${{ steps.docker_build.outputs.digest }}
          push-to-registry: true
  