name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Aktiviert bei Pushes auf den Main-Branch
  workflow_dispatch:  # Ermöglicht manuelle Aktivierung

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Application  # Angenommen, das Dockerfile befindet sich im Verzeichnis 'Application'
          file: ./Application/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/videoschnitt-engine:latest
