name: Publish Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  release:
    types: [prereleased]
  workflow_dispatch:

# Defines two custom environment variables for the workflow.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: videoschnitt.engine

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GitHub Container Registry
        id: docker_build_ghcr
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        id: docker_build_dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Generate artifact attestation for GitHub Container Registry
        uses: actions/attest-build-provenance@v1
        with:
            subject-name: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
            subject-digest: ${{ steps.docker_build_ghcr.outputs.digest }}
            push-to-registry: true

      - name: Generate artifact attestation for Docker Hub
        uses: actions/attest-build-provenance@v1
        with:
            subject-name: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
            subject-digest: ${{ steps.docker_build_dockerhub.outputs.digest }}
            push-to-registry: true
